spring.application.name=Placementmanagement_Certificate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/vkit
spring.datasource.username=postgres
spring.datasource.password=61214
server.port=8088
